ARG version

FROM asteroid_rush/base:$version

ENTRYPOINT ["/opt/eosio/bin/keosd", \
                 "--wallet-dir=/opt/eosio/bin/data-dir", "--http-validate-host=false", \
                 "--http-server-address=0.0.0.0:8020", "--http-alias=localhost:8020" \

          ]