ARG version

FROM asteroid_rush/base:$version
RUN mkdir /certs

ENTRYPOINT ["/opt/eosio/bin/nodeosd.sh", \
                    "--data-dir=/opt/eosio/bin/data-dir", \
                    "--https-server-address=0.0.0.0:8010", \
		    "--http-server-address=0.0.0.0:8013", "--http-alias=localhost:8013", \
                    "--bnet-endpoint=0.0.0.0:8011", "--p2p-listen-endpoint=0.0.0.0:8012" \
            ]
